<?php
require_once __DIR__.'/_init.php'; require_role(['admin']); verify_csrf();
if(isset($_GET['delete'])){ app_query('DELETE FROM users WHERE id=? AND id<>?',[(int)$_GET['delete'],current_user()['id']]); flash('success','Pengguna dihapus.'); redirect('users.php'); }
if($_SERVER['REQUEST_METHOD']==='POST'){
    $id=(int)($_POST['id']??0); $teacher_id=$_POST['teacher_id']!==''?(int)$_POST['teacher_id']:null;
    if($id){ $params=[$_POST['name'],$_POST['username'],$_POST['role'],$teacher_id,isset($_POST['active'])?1:0,$id]; app_query('UPDATE users SET name=?,username=?,role=?,teacher_id=?,active=? WHERE id=?',$params); if(!empty($_POST['password'])) app_query('UPDATE users SET password=? WHERE id=?',[password_hash($_POST['password'],PASSWORD_DEFAULT),$id]); }
    else { app_query('INSERT INTO users(name,username,password,role,teacher_id,active) VALUES(?,?,?,?,?,?)',[$_POST['name'],$_POST['username'],password_hash($_POST['password'],PASSWORD_DEFAULT),$_POST['role'],$teacher_id,isset($_POST['active'])?1:0]); }
    flash('success','Pengguna disimpan.'); redirect('users.php');
}
$edit=null; if(isset($_GET['edit'])) $edit=app_query('SELECT * FROM users WHERE id=?',[(int)$_GET['edit']])->fetch(); $teachers=app_query('SELECT * FROM teachers ORDER BY name')->fetchAll(); $rows=app_query('SELECT u.*,t.name teacher FROM users u LEFT JOIN teachers t ON t.id=u.teacher_id ORDER BY u.id DESC')->fetchAll(); render_header('Pengguna'); ?>
<div class="card"><h2>Form Pengguna</h2><form method="post" class="form two"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><div><label>Nama</label><input name="name" required value="<?= e($edit['name']??'') ?>"></div><div><label>Username</label><input name="username" required value="<?= e($edit['username']??'') ?>"></div><div><label>Password <?= $edit?'(kosongkan jika tidak diganti)':'' ?></label><input name="password" type="password" <?= $edit?'':'required' ?>></div><div><label>Role</label><select name="role"><?php foreach(['admin','kepala_sekolah','supervisor','guru'] as $role): ?><option <?= (($edit['role']??'')===$role)?'selected':'' ?>><?= $role ?></option><?php endforeach; ?></select></div><div><label>Hubungkan Guru</label><select name="teacher_id"><option value="">- Tidak ada -</option><?php foreach($teachers as $t): ?><option value="<?= $t['id'] ?>" <?= (($edit['teacher_id']??'')==$t['id'])?'selected':'' ?>><?= e($t['name']) ?></option><?php endforeach; ?></select></div><div><label><input type="checkbox" name="active" <?= (($edit['active']??1)?'checked':'') ?>> Aktif</label></div><button>Simpan</button></form></div>
<div class="card" style="margin-top:16px"><table><tr><th>Nama</th><th>Username</th><th>Role</th><th>Guru</th><th>Status</th><th>Aksi</th></tr><?php foreach($rows as $r): ?><tr><td><?= e($r['name']) ?></td><td><?= e($r['username']) ?></td><td><span class="badge"><?= e($r['role']) ?></span></td><td><?= e($r['teacher']) ?></td><td><?= $r['active']?'Aktif':'Nonaktif' ?></td><td><a class="btn small secondary" href="?edit=<?= $r['id'] ?>">Edit</a> <a class="btn small danger" data-confirm="Hapus?" href="?delete=<?= $r['id'] ?>">Hapus</a></td></tr><?php endforeach; ?></table></div><?php render_footer(); ?>
